name: deploy-smarterasp
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # Self-contained publish (no host runtime required)
      - name: Publish (self-contained win-x64)
        run: dotnet publish src/ScottMo.Web/ScottMo.Web.csproj -c Release -o publish -r win-x64 --self-contained true /p:PublishReadyToRun=true

      - name: Ensure stdout log folder exists
        shell: pwsh
        run: New-Item -ItemType Directory -Path "publish/logs" -Force | Out-Null

      - name: Inject connection string into web.config
        shell: pwsh
        run: |
          $web = "publish/web.config"
          [xml]$x = Get-Content $web
          $ancm = $x.configuration.'system.webServer'.aspNetCore
          if (-not $ancm) { throw "aspNetCore element not found in web.config" }
          $envs = $ancm.environmentVariables
          if (-not $envs) { $envs = $x.CreateElement("environmentVariables"); $ancm.AppendChild($envs) | Out-Null }
          foreach ($n in @($envs.environmentVariable)) { if ($n.name -eq "Default__ConnectionString") { $envs.RemoveChild($n) | Out-Null } }
          $e = $x.CreateElement("environmentVariable")
          $e.SetAttribute("name","Default__ConnectionString")
          $e.SetAttribute("value","${{ secrets.SASP_DB_CONNSTR }}")
          $envs.AppendChild($e) | Out-Null
          $x.Save($web)

      - name: Add deploy marker
        shell: pwsh
        run: |
          $sha = "${{ github.sha }}".Substring(0,7)
          Set-Content -Path "publish/version.txt" -Value "deployed $((Get-Date).ToString('u')) / $sha"

      - name: FTP Deploy to SmarterASP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.SASP_FTPS_SERVER }}      # e.g. win8139.site4now.net
          username: ${{ secrets.SASP_FTPS_USER }}       # smontgomery-001
          password: ${{ secrets.SASP_FTPS_PASSWORD }}
          protocol: ftps                               # if data socket drops, switch to ftps-legacy + port 990
          port: 21
          local-dir: "publish/"
          server-dir: ${{ secrets.SASP_SERVER_DIR }}   # e.g. scottmo-dev/ or wwwroot/
          log-level: verbose
          state-name: ".ftp-deploy-sync-state.json"
